remote_theme: pages-themes/hacker@v0.2.0
title: SMART-TAKA APP
description: Climate mitigation through waste management.

# Theme settings
minima:
 skin: default # "default", "dark", or "dark-dimmed"

# Build settings
markdown: kramdown
permalink: pretty

# Markdown settings
kramdown:
 input: GFM
 hard_wrap: false
 auto_ids: true
 footnote_nr: 1
 entity_output: as_char
 toc_levels: 1..6
 smart_quotes: lsquo,rsquo,ldquo,rdquo
 enable_coderay: false
#plugins:
  #- jekyll-remote-theme
