remote_theme: pages-themes/cayman@v0.2.0
title: RIFAZ SOLUTIONS
description: Find revolutionary products for your business case.

plugins:
  - jekyll-remote-theme

url: https://ridhiwan.github.io

nav:
  - title: Home
    url: /docs
  - title: Smart-Taka
    url: /docs/pages/SMART_TAKA.md
  - title: DashyB
    url: /docs/pages/DASHYB.md
