theme: jekyll-theme-cayman
title: RIFAZ SOLUTIONS
description: Find revolutionary products for your business case.

markdown: kramdown
kramdown:
  input: GFM

exclude: ['README.md', '_config.yml']

permalink: /:title/

navigation:
  - title: Home
    url: /docs
  - title: Smart-Taka
    url: /docs/pages/SMART_TAKA.md
  - title: DashyB
    url: /docs/pages/DASHYB.md
